# 张量、函数与计算图


In [14]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [15]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

# Gradient function for z = <AddBackward0 object at 0x109db3f10>
# Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x109d37e50>

Gradient function for z = <AddBackward0 object at 0x16a2a3fa0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x16a2a3d90>


# 计算梯度

In [ ]:
loss.backward()
print(w.grad)
print(b.grad)

# tensor([[0.0032, 0.0023, 0.1093],
#         [0.0032, 0.0023, 0.1093],
#         [0.0032, 0.0023, 0.1093],
#         [0.0032, 0.0023, 0.1093],
#         [0.0032, 0.0023, 0.1093]])
# tensor([0.0032, 0.0023, 0.1093])

tensor([[0.0032, 0.0023, 0.1093],
        [0.0032, 0.0023, 0.1093],
        [0.0032, 0.0023, 0.1093],
        [0.0032, 0.0023, 0.1093],
        [0.0032, 0.0023, 0.1093]])
tensor([0.0032, 0.0023, 0.1093])


# 禁用梯度

In [ ]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

# True
# False

True
False


In [ ]:
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

# False

False
